### ISSUE TITLE
Maybe replace app example images?

### ISSUE THREAD

**Issue by jtagcat** [popey/makealinux.app#10]
VSCode, Firefox and others mentioned on the page are large.

This could discourage making an app, as many apps can be very light, small, and so on. "So _this_ is an app. You expect me to make VSCode in a few days?"

**Comment by popey** [comment]
The screenshot of VSCode is there as an example of how you make an app, not what you make. It shows some vala source code of the Akira design application. Akira is also a complex program, but I picked it because it's something that the developers wanted to make, so they got a bunch of friends and built it. It's not finished, not as big as VSCode and might be something a new developer may want to get involved with.

I chose VSCode over something like nano, emacs or vim, to show that coding doesn't have to mean you have to whip yourself to wirte code. It's possible to code in a pleasant environment. Arguments about which text editor it should show can go to /dev/null, I don't care :D. I mean, maybe I could change the screenshot for VS Codium (the free software, non-tracking version of VS Code) but that's not the point of the site. The site doesn't actually suggest you have to make Free Software, just that Linux needs more apps, and there are resources available to get started. The license is up to the developer.

The "Firefox" isn't actually a screenshot of Firefox. That's a banner for the Firefox snap as shown in GNOME Software. It's to indicate that there are software storefronts like GNOME Software, App Center on elementary OS and Pop Shop on Pop!_!!OS!! which can be a showcase for your creations.

**Comment by jtagcat** [comment]
VSCode: With this background, yes this is fine; but at a glance, it did seem like a generic screenshot of an open-source program. That's my first impression though, am fine with it being ignored, but do note if somebody else spots this. Take it a notch further, VSCodium!

> which can be a showcase for your creations.

I have seen storefronts showcase nice one-developer app, but in that example, it would be nice to see something smaller (again, <6 months with (few) developer(s)).

**Comment by popey** [comment]
Thanks for the issue. Sorry, it's taken a while to get back to this. 
I've decided to reboot this initiative and move the repo to a new location while we work on it. 

I hope you'll join us there. 

https://github.com/makealinuxapp/makealinuxapp
